//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelAudition.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carburant
    {
        public Carburant()
        {
            this.ClientFournisseurs = new HashSet<ClientFournisseur>();
        }
    
        public int CarburantId { get; set; }
        public string NomFr { get; set; }
        public string NomAn { get; set; }
        public bool Actif { get; set; }
    
        public virtual ICollection<ClientFournisseur> ClientFournisseurs { get; set; }
    }
}
