//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelAudition.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientFournisseur
    {
        public int ClientFournisseurId { get; set; }
        public int ClientId { get; set; }
        public int FournisseurId { get; set; }
        public int CarburantId { get; set; }
        public int VolumeId { get; set; }
        public decimal Marge { get; set; }
        public Nullable<System.DateTime> DateFinContrat { get; set; }
        public int ActiviteId { get; set; }
        public Nullable<System.DateTime> DateDebutContrat { get; set; }
        public int Statut { get; set; }
        public string Commentaire { get; set; }
    
        public virtual Activite Activite { get; set; }
        public virtual Carburant Carburant { get; set; }
        public virtual Client Client { get; set; }
        public virtual Fournisseur Fournisseur { get; set; }
        public virtual Volume Volume { get; set; }
    }
}
