//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelAudition.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxe
    {
        public int TaxeId { get; set; }
        public string TaxeCode { get; set; }
        public System.DateTime TauxDate { get; set; }
        public string Nom { get; set; }
        public float Taux { get; set; }
    }
}
