//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelAudition.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanadaDailyRacksRaw
    {
        public int IdCanadianDailyRackRaw { get; set; }
        public string Date { get; set; }
        public int CityCode { get; set; }
        public string CityName { get; set; }
        public string Supplier { get; set; }
        public string IndBrand { get; set; }
        public string Product { get; set; }
        public string Price { get; set; }
        public string Move { get; set; }
        public string MoveDate { get; set; }
    }
}
