//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelAudition.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.ClientCamions = new HashSet<ClientCamion>();
            this.ClientFournisseurs = new HashSet<ClientFournisseur>();
        }
    
        public int ClientId { get; set; }
        public string Nom { get; set; }
        public string Telephone { get; set; }
        public string Inter { get; set; }
        public string FAX { get; set; }
        public string Email { get; set; }
        public string Adresse1 { get; set; }
        public string Adresse2 { get; set; }
        public Nullable<int> VilleId { get; set; }
        public string CodePostal { get; set; }
        public string ContactNom { get; set; }
        public string ContactTelephone { get; set; }
        public string ContactInter { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<int> LangueId { get; set; }
        public Nullable<int> NombreCamion { get; set; }
        public Nullable<int> NombreHeureOperation { get; set; }
        public Nullable<int> NombreEmploye { get; set; }
        public Nullable<System.DateTime> DateCreationCompagnie { get; set; }
        public string NomCompagnie { get; set; }
        public bool Actif { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public Nullable<System.DateTime> DateModification { get; set; }
        public string Utilisateur { get; set; }
    
        public virtual ICollection<ClientCamion> ClientCamions { get; set; }
        public virtual Langue Langue { get; set; }
        public virtual Ville Ville { get; set; }
        public virtual ICollection<ClientFournisseur> ClientFournisseurs { get; set; }
    }
}
