//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelAudition.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCamion
    {
        public int ClientCamionId { get; set; }
        public int ClientId { get; set; }
        public int CamionId { get; set; }
    
        public virtual Camion Camion { get; set; }
        public virtual Client Client { get; set; }
    }
}
