//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelAudition.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fournisseur
    {
        public Fournisseur()
        {
            this.ClientFournisseurs = new HashSet<ClientFournisseur>();
        }
    
        public int FournisseurId { get; set; }
        public string Nom { get; set; }
        public string Telephone { get; set; }
        public string Inter { get; set; }
        public string FAX { get; set; }
        public string Email { get; set; }
        public string Adresse1 { get; set; }
        public string Adresse2 { get; set; }
        public Nullable<int> VilleId { get; set; }
        public string CodePostal { get; set; }
        public Nullable<int> ProvinceId { get; set; }
    
        public virtual ICollection<ClientFournisseur> ClientFournisseurs { get; set; }
        public virtual Province Province { get; set; }
        public virtual Ville Ville { get; set; }
    }
}
