//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelAudition.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class np38965_FAEntities : DbContext
    {
        public np38965_FAEntities()
            : base("name=np38965_FAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Activite> Activites { get; set; }
        public virtual DbSet<Camion> Camions { get; set; }
        public virtual DbSet<ClientCamion> ClientCamions { get; set; }
        public virtual DbSet<Carburant> Carburants { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientFournisseur> ClientFournisseurs { get; set; }
        public virtual DbSet<Devise> Devises { get; set; }
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<Fournisseur> Fournisseurs { get; set; }
        public virtual DbSet<Langue> Langues { get; set; }
        public virtual DbSet<Pay> Pays { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Ravitaillement> Ravitaillements { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Taxe> Taxes { get; set; }
        public virtual DbSet<Ville> Villes { get; set; }
        public virtual DbSet<Volume> Volumes { get; set; }
        public virtual DbSet<CanadaDailyRacksRaw> CanadaDailyRacksRaws { get; set; }
    }
}
