//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelAudition.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Langue
    {
        public Langue()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public int LangueId { get; set; }
        public string LangueCode { get; set; }
        public string NomFr { get; set; }
        public string NomAn { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
    }
}
