//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelAudition.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        public Province()
        {
            this.Fournisseurs = new HashSet<Fournisseur>();
            this.Villes = new HashSet<Ville>();
        }
    
        public int ProvinceId { get; set; }
        public string ProvinceCode { get; set; }
        public string NomFr { get; set; }
        public string NomAn { get; set; }
        public Nullable<int> PaysId { get; set; }
    
        public virtual ICollection<Fournisseur> Fournisseurs { get; set; }
        public virtual Pay Pay { get; set; }
        public virtual ICollection<Ville> Villes { get; set; }
    }
}
