//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelAudition.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ville
    {
        public Ville()
        {
            this.Clients = new HashSet<Client>();
            this.Fournisseurs = new HashSet<Fournisseur>();
        }
    
        public int VilleId { get; set; }
        public int VilleCode { get; set; }
        public string Nom { get; set; }
        public string Désignation { get; set; }
        public string MRCCM { get; set; }
        public string Région { get; set; }
        public Nullable<int> ProvinceId { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<Fournisseur> Fournisseurs { get; set; }
        public virtual Province Province { get; set; }
    }
}
